import type { Letter } from './types';

export const ALPHABET_DATA: Letter[] = [
  { letter: 'A', word: 'Apple', image: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/a.mp3', wordSound: '/sounds/apple.mp3' },
  { letter: 'B', word: 'Ball', image: 'https://images.pexels.com/photos/47730/the-ball-stadion-football-the-pitch-47730.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/b.mp3', wordSound: '/sounds/ball.mp3' },
  { letter: 'C', word: 'Cat', image: 'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/c.mp3', wordSound: '/sounds/cat.mp3' },
  { letter: 'D', word: 'Dog', image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/d.mp3', wordSound: '/sounds/dog.mp3' },
  { letter: 'E', word: 'Elephant', image: 'https://images.pexels.com/photos/66898/elephant-cub-tsavo-kenya-66898.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/e.mp3', wordSound: '/sounds/elephant.mp3' },
  { letter: 'F', word: 'Fish', image: 'https://images.pexels.com/photos/128756/pexels-photo-128756.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/f.mp3', wordSound: '/sounds/fish.mp3' },
  { letter: 'G', word: 'Gym', image: 'https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/g.mp3', wordSound: '/sounds/gym.mp3' },
  { letter: 'H', word: 'House', image: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/h.mp3', wordSound: '/sounds/house.mp3' },
  { letter: 'I', word: 'Ice Cream', image: 'https://images.pexels.com/photos/1352278/pexels-photo-1352278.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/i.mp3', wordSound: '/sounds/ice-cream.mp3' },
  { letter: 'J', word: 'Juice', image: 'https://images.pexels.com/photos/792613/pexels-photo-792613.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/j.mp3', wordSound: '/sounds/juice.mp3' },
  { letter: 'K', word: 'Kitchen', image: 'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/k.mp3', wordSound: '/sounds/kitchen.mp3' },
  { letter: 'L', word: 'Lion', image: 'https://images.pexels.com/photos/247502/pexels-photo-247502.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/l.mp3', wordSound: '/sounds/lion.mp3' },
  { letter: 'M', word: 'Man', image: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/m.mp3', wordSound: '/sounds/man.mp3' },
  { letter: 'N', word: 'Night', image: 'https://images.pexels.com/photos/998641/pexels-photo-998641.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/n.mp3', wordSound: '/sounds/night.mp3' },
  { letter: 'O', word: 'Ocean', image: 'https://images.pexels.com/photos/1001682/pexels-photo-1001682.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/o.mp3', wordSound: '/sounds/ocean.mp3' },
  { letter: 'P', word: 'Pizza', image: 'https://images.pexels.com/photos/1146760/pexels-photo-1146760.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/p.mp3', wordSound: '/sounds/pizza.mp3' },
  { letter: 'Q', word: 'Question', image: 'https://images.pexels.com/photos/356079/pexels-photo-356079.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/q.mp3', wordSound: '/sounds/question.mp3' },
  { letter: 'R', word: 'Rabbit', image: 'https://images.pexels.com/photos/4001296/pexels-photo-4001296.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/r.mp3', wordSound: '/sounds/rabbit.mp3' },
  { letter: 'S', word: 'Soup', image: 'https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/s.mp3', wordSound: '/sounds/soup.mp3' },
  { letter: 'T', word: 'Tiger', image: 'https://images.pexels.com/photos/302304/pexels-photo-302304.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/t.mp3', wordSound: '/sounds/tiger.mp3' },
  { letter: 'U', word: 'Universe', image: 'https://images.pexels.com/photos/1252890/pexels-photo-1252890.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/u.mp3', wordSound: '/sounds/universe.mp3' },
  { letter: 'V', word: 'Vegetables', image: 'https://images.pexels.com/photos/1300972/pexels-photo-1300972.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/v.mp3', wordSound: '/sounds/vegetables.mp3' },
  { letter: 'W', word: 'Woman', image: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/w.mp3', wordSound: '/sounds/woman.mp3' },
  { letter: 'X', word: 'X-box', image: 'https://images.pexels.com/photos/1298601/pexels-photo-1298601.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/x.mp3', wordSound: '/sounds/x-box.mp3' },
  { letter: 'Y', word: 'Yoga', image: 'https://images.pexels.com/photos/3822365/pexels-photo-3822365.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/y.mp3', wordSound: '/sounds/yoga.mp3' },
  { letter: 'Z', word: 'Zoom Lens', image: 'https://images.pexels.com/photos/122400/pexels-photo-122400.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=1', letterSound: '/sounds/z.mp3', wordSound: '/sounds/zoom-lens.mp3' },
];

export const TILE_GRADIENTS = [
    'bg-gradient-to-br from-red-500 to-orange-400',
    'bg-gradient-to-br from-orange-500 to-amber-400',
    'bg-gradient-to-br from-amber-500 to-yellow-400',
    'bg-gradient-to-br from-yellow-500 to-lime-400',
    'bg-gradient-to-br from-lime-500 to-green-400',
    'bg-gradient-to-br from-green-500 to-emerald-400',
    'bg-gradient-to-br from-emerald-500 to-teal-400',
    'bg-gradient-to-br from-teal-500 to-cyan-400',
    'bg-gradient-to-br from-cyan-500 to-sky-400',
    'bg-gradient-to-br from-sky-500 to-blue-400',
    'bg-gradient-to-br from-blue-500 to-indigo-400',
    'bg-gradient-to-br from-indigo-500 to-violet-400',
    'bg-gradient-to-br from-violet-500 to-purple-400',
    'bg-gradient-to-br from-purple-500 to-fuchsia-400',
    'bg-gradient-to-br from-fuchsia-500 to-pink-400',
    'bg-gradient-to-br from-pink-500 to-rose-400',
    'bg-gradient-to-br from-rose-500 to-red-400',
    'bg-gradient-to-br from-orange-400 to-yellow-500',
    'bg-gradient-to-br from-lime-400 to-emerald-500',
    'bg-gradient-to-br from-teal-400 to-sky-500',
    'bg-gradient-to-br from-blue-400 to-violet-500',
    'bg-gradient-to-br from-purple-400 to-pink-500',
    'bg-gradient-to-br from-rose-400 to-orange-500',
    'bg-gradient-to-br from-yellow-400 to-green-500',
    'bg-gradient-to-br from-cyan-400 to-indigo-500',
    'bg-gradient-to-br from-fuchsia-400 to-red-500',
];
